/**
 * dAvePi client runtime. Hand-written; the matching `davepi.ts`
 * is generated by `davepi gen-client`. This file ships once
 * alongside the regenerated client.
 *
 * Goals: dependency-light, fetch-based, no transitive runtime
 * surprises. The generator emits `import { ... } from './davepi-runtime'`
 * — every helper a generated client needs lives here.
 */

export interface FileMeta {
  key: string;
  bucket: string | null;
  size: number;
  contentType: string;
  originalName: string;
  uploadedAt: string;
  url?: string;
}

export type AvailableTransitions = Record<string, string[]>;

export interface ApiOptions {
  /** Base URL for the API (e.g. `https://api.example.com`). */
  baseUrl?: string;
  /**
   * Synchronous or async getter for the JWT bearer token. Called
   * before every request so a refreshed token gets picked up
   * automatically.
   */
  getToken?: () => string | Promise<string>;
  /**
   * Public client ID identifying this frontend (e.g.
   * `pk_storefront_live_abc123`). Sent on every request as
   * `X-Client-Id`. Client IDs are identifiers, NOT secrets — they
   * are meant to be baked into SPA bundles and are world-readable.
   * The server resolves them to a role and applies the role's ACL +
   * mandatory scope filter (see `schema.acl.scope` in AGENTS.md).
   * Used to expose subsets of collections (published products,
   * future appointments, etc.) to unauthenticated callers. When
   * both `clientId` and a Bearer token are present, the Bearer wins
   * for authorisation; the client ID stays attached as audit
   * context.
   */
  clientId?: string;
  /**
   * Custom fetch implementation (for Node, Cloudflare Workers,
   * tests). Defaults to global fetch.
   */
  fetch?: typeof fetch;
  /**
   * Optional default headers merged into every request.
   */
  headers?: Record<string, string>;
}

export interface ListParams<TInclude extends string = never> {
  filter?: Record<string, unknown>;
  page?: number;
  // NB: page size is server-controlled (PAGE_SIZE env var). The
  // server ignores any client-supplied perPage, so we don't pretend
  // to support one here. Use `ListResponse.perPage` to read the
  // size the server actually applied.
  sort?: string;
  q?: string;
  include?: TInclude[];
  includeDeleted?: boolean;
}

export interface ListResponse<T> {
  results: T[];
  totalResults: number;
  page: number;
  perPage: number;
  totalPages?: number;
  nextPage?: number;
  prevPage?: number;
}

export interface IdempotentCreateOpts {
  idempotencyKey?: string;
}

export interface DeleteResult {
  acknowledged: boolean;
  deletedCount?: number;
  softDeleted?: boolean;
}

export interface AuditEntry {
  _id: string;
  userId: string;
  resource: string;
  recordId: string;
  action: 'create' | 'update' | 'delete' | 'restore' | 'transition';
  before: unknown;
  after: unknown;
  diff: Record<string, [unknown, unknown]> | null;
  reqId: string | null;
  ip: string | null;
  userAgent: string | null;
  createdAt: string;
}

export class DavepiError extends Error {
  status: number;
  code: string;
  details?: unknown;
  constructor(status: number, code: string, message: string, details?: unknown) {
    super(message);
    this.name = 'DavepiError';
    this.status = status;
    this.code = code;
    this.details = details;
  }
}

interface HttpClient {
  request<T>(opts: {
    method: string;
    path: string;
    query?: Record<string, unknown>;
    body?: unknown;
    headers?: Record<string, string>;
  }): Promise<T>;
  baseUrl: string;
  fetchImpl: typeof fetch;
  getToken: () => string | Promise<string> | undefined;
  defaultHeaders: Record<string, string>;
}

export function buildHttpClient(opts: ApiOptions): HttpClient {
  const baseUrl = (opts.baseUrl || '').replace(/\/+$/, '');
  const fetchImpl = opts.fetch || (globalThis.fetch as typeof fetch);
  const getToken = opts.getToken || (() => undefined as unknown as string);
  const defaultHeaders = { ...(opts.headers || {}) };
  if (opts.clientId) defaultHeaders['X-Client-Id'] = opts.clientId;

  async function request<T>({
    method,
    path,
    query,
    body,
    headers,
  }: {
    method: string;
    path: string;
    query?: Record<string, unknown>;
    body?: unknown;
    headers?: Record<string, string>;
  }): Promise<T> {
    const qs = query ? buildQuery(query) : '';
    const url = baseUrl + path + (qs ? `?${qs}` : '');
    const token = await getToken();
    const finalHeaders: Record<string, string> = {
      'Content-Type': 'application/json',
      ...defaultHeaders,
      ...(headers || {}),
    };
    if (token) finalHeaders.Authorization = `Bearer ${token}`;
    const res = await fetchImpl(url, {
      method,
      headers: finalHeaders,
      body: body == null ? undefined : JSON.stringify(body),
    });
    if (res.status === 204) return undefined as T;
    const parsed = await readResponseBody(res);
    if (!res.ok) throwApiError(res, parsed);
    return parsed as T;
  }

  return { request, baseUrl, fetchImpl, getToken, defaultHeaders };
}

/**
 * Parse a Response body as JSON when possible, falling back to the
 * raw text string on parse failure (matches the contract of the
 * shared `request()` flow). Used by file-upload / file-fetch
 * helpers so a non-JSON error body doesn't surface as an opaque
 * SyntaxError.
 */
async function readResponseBody(res: Response): Promise<unknown> {
  const text = await res.text();
  if (!text) return null;
  try {
    return JSON.parse(text);
  } catch {
    return text;
  }
}

/**
 * Shape any non-2xx response into a typed `DavepiError`. Reads the
 * canonical `{ error: { code, message, details } }` body when the
 * server emits one; falls back to status text and raw body
 * otherwise. Shared between the standard `request()` flow and the
 * file helpers below so error shape is identical across surfaces.
 */
function throwApiError(res: Response, parsed: unknown): never {
  const body =
    parsed && typeof parsed === 'object' && 'error' in (parsed as object)
      ? (parsed as { error: { code?: string; message?: string; details?: unknown } }).error
      : { code: 'UNKNOWN', message: typeof parsed === 'string' ? parsed : res.statusText };
  throw new DavepiError(
    res.status,
    body?.code || 'UNKNOWN',
    body?.message || res.statusText,
    body?.details
  );
}

function buildQuery(q: Record<string, unknown>): string {
  const params = new URLSearchParams();
  for (const [k, v] of Object.entries(q)) {
    if (v == null) continue;
    if (Array.isArray(v)) {
      if (v.length) params.set(k, v.join(','));
    } else if (typeof v === 'object') {
      // Mongo-querystring accepts JSON-encoded operators —
      // serialise sub-objects as JSON so `{ amount: { $gte: 10 } }`
      // roundtrips correctly.
      params.set(k, JSON.stringify(v));
    } else {
      params.set(k, String(v));
    }
  }
  return params.toString();
}

interface ResourceConfig {
  path: string;
  version: string;
  softDelete: boolean;
  audit: boolean;
  searchable: boolean;
  aggregations: string[];
  relations: string[];
  stateMachineFields: string[];
  fileFields: string[];
}

/**
 * Factory used by the generated client to build a per-resource
 * client. Accepts the type parameters from the generator (TRead /
 * TWrite / TInclude) so each method's input/output stays typed.
 */
export function makeResourceClient<TRead, TWrite, TInclude extends string>(
  client: HttpClient,
  cfg: ResourceConfig
): unknown {
  const base = `/api/${cfg.version}/${cfg.path}`;
  const result: Record<string, unknown> = {
    list(params: ListParams<TInclude> = {}) {
      const q: Record<string, unknown> = { ...(params.filter || {}) };
      if (params.page != null) q.__page = params.page;
      if (params.sort) q.__sort = params.sort;
      if (params.q) q.__q = params.q;
      if (params.include && params.include.length) q.__include = params.include;
      if (params.includeDeleted) q.__includeDeleted = 'true';
      return client.request<ListResponse<TRead>>({ method: 'GET', path: base, query: q });
    },
    get(id: string, opts: { include?: TInclude[] } = {}) {
      const q: Record<string, unknown> = {};
      if (opts.include && opts.include.length) q.__include = opts.include;
      return client.request<TRead>({ method: 'GET', path: `${base}/${id}`, query: q });
    },
    create(record: TWrite, opts: IdempotentCreateOpts = {}) {
      const headers: Record<string, string> = {};
      if (opts.idempotencyKey) headers['Idempotency-Key'] = opts.idempotencyKey;
      return client.request<TRead>({ method: 'POST', path: base, body: record, headers });
    },
    update(id: string, record: Partial<TWrite>) {
      return client.request<TRead>({ method: 'PUT', path: `${base}/${id}`, body: record });
    },
    delete(id: string) {
      return client.request<DeleteResult>({ method: 'DELETE', path: `${base}/${id}` });
    },
  };

  if (cfg.softDelete) {
    result.restore = (id: string) =>
      client.request<void>({ method: 'POST', path: `${base}/${id}/restore` });
  }
  if (cfg.audit) {
    result.history = (
      id: string,
      params: { page?: number } = {}
    ) => {
      // page size is server-controlled (PAGE_SIZE env); same as
      // list — there's no `perPage` to pass through.
      const q: Record<string, unknown> = {};
      if (params.page != null) q.__page = params.page;
      return client.request<ListResponse<AuditEntry>>({
        method: 'GET',
        path: `${base}/${id}/history`,
        query: q,
      });
    };
  }
  if (cfg.searchable) {
    result.search = (q: string, params: ListParams<TInclude> = {}) => {
      const merged = { ...params, q };
      return (result.list as (p: ListParams<TInclude>) => Promise<ListResponse<TRead>>)(merged);
    };
  }
  for (const aggName of cfg.aggregations) {
    result[aggName] = (args: Record<string, unknown> = {}) =>
      client.request<unknown[]>({
        method: 'GET',
        path: `${base}/aggregations/${aggName}`,
        query: args,
      });
  }
  for (const relName of cfg.relations) {
    result[relName] = async (id: string) => {
      const wrapper = await client.request<TRead>({
        method: 'GET',
        path: `${base}/${id}`,
        query: { __include: [relName] },
      });
      return (wrapper as Record<string, unknown>)[relName];
    };
  }
  for (const fieldName of cfg.stateMachineFields) {
    const verb = `transition${fieldName.charAt(0).toUpperCase()}${fieldName.slice(1)}`;
    result[verb] = (id: string, to: string) =>
      client.request<TRead>({
        method: 'PUT',
        path: `${base}/${id}`,
        body: { [fieldName]: to },
      });
  }
  for (const fieldName of cfg.fileFields) {
    const verb = fieldName.charAt(0).toUpperCase() + fieldName.slice(1);
    result[`upload${verb}`] = async (id: string, file: Blob | File) => {
      const fd = new FormData();
      fd.append('file', file);
      const token = await client.getToken();
      const headers: Record<string, string> = { ...client.defaultHeaders };
      if (token) headers.Authorization = `Bearer ${token}`;
      const url = client.baseUrl + `${base}/${id}/${fieldName}`;
      const res = await client.fetchImpl(url, { method: 'POST', headers, body: fd });
      const parsed = await readResponseBody(res);
      if (!res.ok) throwApiError(res, parsed);
      return parsed as FileMeta;
    };
    result[`fetch${verb}Url`] = async (id: string) => {
      const token = await client.getToken();
      const headers: Record<string, string> = { ...client.defaultHeaders };
      if (token) headers.Authorization = `Bearer ${token}`;
      // The endpoint replies with a 3xx redirect to a public /
      // short-lived signed URL. Use `redirect: 'manual'` so we
      // read the Location header instead of following the redirect
      // (the storage URL doesn't accept our Bearer token).
      const res = await client.fetchImpl(client.baseUrl + `${base}/${id}/${fieldName}`, {
        method: 'GET',
        headers,
        redirect: 'manual',
      });
      const REDIRECT = new Set([301, 302, 303, 307, 308]);
      if (REDIRECT.has(res.status)) {
        const loc = res.headers.get('Location');
        if (loc) return loc;
        // Redirect status without a Location is a server bug —
        // surface it as DavepiError rather than returning null.
        throw new DavepiError(
          res.status,
          'UNKNOWN',
          'No Location header on file URL response'
        );
      }
      // Non-3xx responses (401 missing auth, 404 missing file, etc.)
      // carry the canonical { error: { code, message, details } }
      // body — same shape as every other handler. Parse and throw.
      const parsed = await readResponseBody(res);
      throwApiError(res, parsed);
    };
    result[`delete${verb}`] = (id: string) =>
      client.request<void>({ method: 'DELETE', path: `${base}/${id}/${fieldName}` });
  }

  return result;
}
