const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const {
  generateClient,
  toPascalCase,
  mapBareType,
} = require('../utils/clientGen');

describe('clientGen: pure helpers', () => {
  test('toPascalCase splits on non-identifier chars', () => {
    expect(toPascalCase('account')).toBe('Account');
    expect(toPascalCase('rel_account')).toBe('RelAccount');
    expect(toPascalCase('mcp-doc')).toBe('McpDoc');
  });

  test('mapBareType maps the standard scalars and array shorthand', () => {
    expect(mapBareType(String)).toBe('string');
    expect(mapBareType(Number)).toBe('number');
    expect(mapBareType(Boolean)).toBe('boolean');
    expect(mapBareType(Date)).toBe('string');
    expect(mapBareType([String])).toBe('string[]');
    expect(mapBareType([Number])).toBe('number[]');
    expect(mapBareType({ type: String })).toBe('string');
    expect(mapBareType('Mixed')).toBe('unknown');
  });
});

describe('clientGen: generated TypeScript', () => {
  // A small fixture covering every shape the generator branches on:
  // required + optional fields, computed read-only field, file
  // field, state machine, relations on both sides, aggregation,
  // searchable field, soft-delete + audit defaults.
  const fixture = [
    {
      s: {
        path: 'account',
        collection: 'account',
        version: 'v1',
        fields: [
          { name: 'userId', type: String, required: true },
          { name: 'name', type: String, required: true, searchable: true },
          { name: 'description', type: String },
          {
            name: 'fullName',
            type: String,
            computed: (r) => r.name,
            description: 'Convenience name',
          },
          {
            name: 'logo',
            type: 'File',
            file: { maxBytes: 1024, accept: ['image/*'], access: 'public' },
          },
          {
            name: 'status',
            type: String,
            stateMachine: {
              initial: 'draft',
              states: ['draft', 'review', 'approved'],
              transitions: { draft: ['review'], review: ['approved'], approved: [] },
            },
          },
        ],
        relations: {
          contacts: { hasMany: 'contact', foreignKey: 'accountId' },
        },
        aggregations: [
          {
            name: 'totalsByMonth',
            params: { from: { type: 'date', required: true } },
            pipeline: [{ $count: 'n' }],
          },
        ],
      },
    },
    {
      s: {
        path: 'contact',
        collection: 'contact',
        version: 'v1',
        fields: [
          { name: 'userId', type: String, required: true },
          { name: 'accountId', type: String, required: true },
          { name: 'name', type: String, required: true },
        ],
        relations: {
          account: { belongsTo: 'account', localKey: 'accountId' },
        },
      },
    },
  ];

  const out = generateClient(fixture, { baseUrl: 'https://api.example.com' });

  test('emits the generated header and runtime import', () => {
    expect(out).toMatch(/Generated by `davepi gen-client`/);
    expect(out).toContain("from './davepi-runtime'");
  });

  test('Account read interface includes computed (readonly), file (FileMeta), state-machine literal, and availableTransitions', () => {
    expect(out).toMatch(/export interface Account \{[\s\S]*?\}/);
    expect(out).toMatch(/readonly fullName\?: string;/);
    expect(out).toMatch(/logo\?: FileMeta;/);
    expect(out).toMatch(/status\?: "draft" \| "review" \| "approved";/);
    expect(out).toMatch(/availableTransitions\?: AvailableTransitions;/);
    // soft-delete and audit are on by default → deletedAt typed
    expect(out).toMatch(/deletedAt: string \| null;/);
  });

  test('Account writeable shape excludes _id, userId, computed, and file fields', () => {
    const m = out.match(/export interface AccountWriteable \{([\s\S]*?)\n\}/);
    expect(m).not.toBeNull();
    const body = m[1];
    expect(body).toContain('name: string;');
    expect(body).toContain('description?: string;');
    expect(body).not.toContain('userId');
    expect(body).not.toContain('fullName'); // computed
    expect(body).not.toContain('logo'); // file
  });

  test('Include type is a literal union when relations exist, never otherwise', () => {
    expect(out).toContain('export type AccountInclude = "contacts";');
    expect(out).toContain('export type ContactInclude = "account";');
  });

  test('Per-resource client includes all generated method signatures', () => {
    expect(out).toMatch(/export interface AccountClient \{[\s\S]*?\}/);
    expect(out).toMatch(/list\(params\?: ListParams<AccountInclude>\): Promise<ListResponse<Account>>/);
    expect(out).toMatch(/create\(record: AccountWriteable, opts\?: IdempotentCreateOpts\): Promise<Account>/);
    expect(out).toMatch(/update\(id: string, record: Partial<AccountWriteable>\): Promise<Account>/);
    expect(out).toMatch(/delete\(id: string\): Promise<DeleteResult>/);
    // soft-delete enabled → restore
    expect(out).toMatch(/restore\(id: string\): Promise<void>/);
    // audit enabled → history
    expect(out).toMatch(/history\(id: string, params\?: \{ page\?: number; perPage\?: number \}\): Promise<ListResponse<AuditEntry>>/);
    // searchable field → search
    expect(out).toMatch(/search\(q: string, params\?: ListParams<AccountInclude>\)/);
    // aggregation
    expect(out).toMatch(/totalsByMonth\(args: \{ from: string;? \}\): Promise<unknown\[\]>/);
    // relation
    expect(out).toMatch(/contacts\(id: string\): Promise<Contact\[\]>/);
    // state-machine transition
    expect(out).toMatch(/transitionStatus\(id: string, to: "draft" \| "review" \| "approved"\): Promise<Account>/);
    // file field
    expect(out).toMatch(/uploadLogo\(id: string, file: Blob \| File\): Promise<FileMeta>/);
    expect(out).toMatch(/fetchLogoUrl\(id: string\): Promise<string>/);
    expect(out).toMatch(/deleteLogo\(id: string\): Promise<void>/);
  });

  test('createDavepiClient factory wires every schema with its config', () => {
    expect(out).toMatch(/export function createDavepiClient\(opts: ApiOptions = \{\}\): DavepiClient/);
    expect(out).toMatch(/account: makeResourceClient<Account, AccountWriteable, AccountInclude>/);
    expect(out).toMatch(/contact: makeResourceClient<Contact, ContactWriteable, ContactInclude>/);
  });

  test('Output is deterministic — schema order is alphabetical', () => {
    const accountIdx = out.indexOf('export interface Account ');
    const contactIdx = out.indexOf('export interface Contact ');
    expect(accountIdx).toBeGreaterThan(0);
    expect(contactIdx).toBeGreaterThan(accountIdx);
  });

  test('Output is deterministic — same input produces byte-identical output', () => {
    const a = generateClient(fixture, { baseUrl: 'https://api.example.com' });
    const b = generateClient(fixture, { baseUrl: 'https://api.example.com' });
    expect(a).toBe(b);
  });

  test('Reordering the input registry does not change the output (alphabetical canonicalisation)', () => {
    const reversed = generateClient(fixture.slice().reverse(), { baseUrl: 'https://api.example.com' });
    expect(out).toBe(reversed);
  });

  test('Generated output matches the committed snapshot byte-for-byte', () => {
    expect(out).toMatchSnapshot();
  });

  test('Schema paths with non-identifier characters get quoted as TS property keys', () => {
    // mcp-doc, 123resource, anything with hyphens — all need to
    // appear as string-literal keys, not bare identifiers, in both
    // the DavepiClient interface and the factory return object.
    const fix = [
      {
        s: {
          path: 'mcp-doc',
          collection: 'mcp_doc',
          version: 'v1',
          fields: [
            { name: 'userId', type: String, required: true },
            { name: 'title', type: String, required: true },
          ],
        },
      },
    ];
    const ts = generateClient(fix, { baseUrl: '' });
    expect(ts).toMatch(/"mcp-doc": McpDocClient;/);
    expect(ts).toMatch(/"mcp-doc": makeResourceClient<McpDoc/);
  });

  test('Two versions of the same path generate distinct symbols + keys', () => {
    const fix = [
      {
        s: {
          path: 'contact',
          collection: 'contact',
          version: 'v1',
          fields: [
            { name: 'userId', type: String, required: true },
            { name: 'name', type: String, required: true },
          ],
        },
      },
      {
        s: {
          path: 'contact',
          collection: 'contact',
          version: 'v2',
          fields: [
            { name: 'userId', type: String, required: true },
            { name: 'name', type: String, required: true },
            { name: 'email', type: String },
          ],
        },
      },
    ];
    const ts = generateClient(fix, { baseUrl: '' });
    // Both symbols are present, no duplicates.
    expect(ts).toMatch(/export interface V1Contact \{/);
    expect(ts).toMatch(/export interface V2Contact \{/);
    expect(ts).not.toMatch(/export interface Contact \{/);
    // Client keys disambiguated with the version prefix and quoted
    // (slash isn't a valid TS identifier char).
    expect(ts).toMatch(/"v1\/contact": V1ContactClient;/);
    expect(ts).toMatch(/"v2\/contact": V2ContactClient;/);
  });

  test('Single-version schemas keep clean (un-prefixed) names', () => {
    // The output we already snapshotted has no version-prefixed
    // symbols — assert that explicitly so future changes can't
    // accidentally start qualifying single-version schemas.
    expect(out).toMatch(/export interface Account \{/);
    expect(out).not.toMatch(/export interface V1Account/);
  });

  test('Generated TypeScript compiles under tsc --noEmit', () => {
    // Spin up a tiny TS project that imports the generated module
    // alongside the runtime, run `tsc --noEmit`, assert no errors.
    // This catches surface-level regressions (typos in emitted
    // type names, missing imports, etc.) without baking the
    // entire output into a snapshot.
    const tsc = path.resolve(__dirname, '..', 'node_modules', '.bin', 'tsc');
    if (!fs.existsSync(tsc)) {
      // typescript is a devDependency of this project, so a normal
      // `npm ci` always provides it. A missing binary means the
      // dev environment is broken — fail loudly rather than skip
      // silently and let a real compile regression sneak through.
      throw new Error(
        `tsc not found at ${tsc}. Run \`npm ci\` to install devDependencies.`
      );
    }
    const tmp = path.resolve(__dirname, '..', '.client-gen-typecheck');
    fs.rmSync(tmp, { recursive: true, force: true });
    fs.mkdirSync(tmp, { recursive: true });
    fs.copyFileSync(
      path.resolve(__dirname, '..', 'client', 'davepi-runtime.ts'),
      path.join(tmp, 'davepi-runtime.ts')
    );
    fs.writeFileSync(path.join(tmp, 'davepi.ts'), out);
    fs.writeFileSync(
      path.join(tmp, 'tsconfig.json'),
      JSON.stringify(
        {
          compilerOptions: {
            target: 'ES2020',
            module: 'commonjs',
            lib: ['ES2020', 'DOM'],
            strict: true,
            noEmit: true,
            esModuleInterop: true,
            skipLibCheck: true,
          },
          include: ['davepi.ts', 'davepi-runtime.ts'],
        },
        null,
        2
      )
    );
    try {
      execSync(`${tsc} -p ${tmp}/tsconfig.json`, { stdio: 'pipe' });
    } finally {
      fs.rmSync(tmp, { recursive: true, force: true });
    }
  });
});
