/**
 * TypeScript client generator. Reads the live schema registry and
 * emits a single .ts file with per-schema interfaces + a factory
 * that returns a fully-typed client object.
 *
 * Pairs with `client/davepi-runtime.ts` — a hand-written companion
 * module that provides the actual `fetch` wrapper, error class,
 * and shared helper types. Generated output imports from
 * './davepi-runtime' so consumers ship one runtime file alongside
 * the regenerated client.
 *
 * Generated output is deterministic: schema order is alphabetical,
 * field order matches the schema declaration, no timestamps. Same
 * schema map produces byte-identical output across runs, so CI diffs
 * stay clean.
 */

const {
  isComputedField,
  computedFieldsOf,
} = require('./computedFields');
const {
  isStateMachineField,
  stateMachineFieldsOf,
} = require('./stateMachine');
const { normalizeRelations } = require('./relations');

const HEADER =
  '// Generated by `davepi gen-client`. Do not edit by hand —\n' +
  '// re-run after a schema change. Pairs with ./davepi-runtime.ts.\n' +
  '/* eslint-disable */\n';

/**
 * Resource path → PascalCase TypeScript interface name.
 *   account     → Account
 *   contact     → Contact
 *   rel_account → RelAccount
 */
function toPascalCase(s) {
  return String(s)
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

const FRAMEWORK_FIELDS = new Set(['_id', 'createdAt', 'updatedAt', 'deletedAt']);

/**
 * Convert a mongoose field type declaration into a TS type string.
 * Handles array shorthand ([String]), the expanded { type } form,
 * native constructors, and a few special cases:
 *
 *   - File field → `FileMeta` (defined in runtime)
 *   - State machine field → literal union of declared states
 *   - Date → `string` (ISO 8601 over the wire; runtime parsers are
 *     out of scope for v1)
 *   - Mixed / unknown → `unknown`
 */
function typeOf(field) {
  if (field.type === 'File') return 'FileMeta';
  if (isStateMachineField(field)) {
    return field.stateMachine.states.map((s) => JSON.stringify(s)).join(' | ');
  }
  return mapBareType(field.type);
}

function mapBareType(t) {
  if (Array.isArray(t)) return `${mapBareType(t[0])}[]`;
  if (t === String || t === 'String') return 'string';
  if (t === Number || t === 'Number') return 'number';
  if (t === Boolean || t === 'Boolean') return 'boolean';
  if (t === Date || t === 'Date') return 'string';
  if (t && typeof t === 'object' && t.type) return mapBareType(t.type);
  return 'unknown';
}

/**
 * Read-shape (response) interface body. Includes computed fields,
 * file metadata, framework fields, and `availableTransitions` for
 * schemas that declare state machines.
 */
function readShapeBody(s, symbolName = (x) => toPascalCase(x.path)) {
  const lines = ['  _id: string;', '  userId: string;'];
  const seen = new Set(['_id', 'userId']);
  for (const f of s.fields || []) {
    if (!f || !f.name || seen.has(f.name)) continue;
    seen.add(f.name);
    const optional = f.required ? '' : '?';
    // Computed fields are server-derived; mark readonly so a TS
    // user can't accidentally assign through `widget.fullName = ...`.
    const readonly = isComputedField(f) ? 'readonly ' : '';
    lines.push(`  ${readonly}${f.name}${optional}: ${typeOf(f)};`);
  }
  // Framework metadata that's not in s.fields but exists on every
  // record. softDelete tombstone is nullable; the timestamps plugin
  // adds createdAt / updatedAt.
  lines.push('  createdAt: string;');
  lines.push('  updatedAt: string;');
  if (s.softDelete !== false) {
    lines.push('  deletedAt: string | null;');
  }
  if (stateMachineFieldsOf(s).length) {
    lines.push('  availableTransitions?: AvailableTransitions;');
  }
  // Relations populated via __include show up as optional fields on
  // the read shape — clients that don't pass include get `undefined`.
  // Target type names go through `symbolName` so cross-version name
  // collisions resolve to the right disambiguated symbol.
  const rels = normalizeRelations(s);
  for (const [name, def] of Object.entries(rels)) {
    if (def.fromShorthand) continue;
    const target = symbolName({ path: def.target, version: s.version });
    if (def.kind === 'hasMany') {
      lines.push(`  ${name}?: ${target}[];`);
    } else {
      lines.push(`  ${name}?: ${target} | null;`);
    }
  }
  return lines.join('\n');
}

/**
 * Writeable-shape (request body) interface body. Excludes computed,
 * framework-stamped, and File fields. State-machine fields are
 * typed as the full state-literal union but in practice the server
 * rejects non-initial values on create — clients should leave them
 * unset.
 */
function writeShapeBody(s) {
  const lines = [];
  for (const f of s.fields || []) {
    if (!f || !f.name) continue;
    if (f.name === 'userId' || f.name === 'accountId') continue;
    if (FRAMEWORK_FIELDS.has(f.name)) continue;
    if (isComputedField(f)) continue;
    if (f.type === 'File') continue;
    const optional = f.required ? '' : '?';
    lines.push(`  ${f.name}${optional}: ${typeOf(f)};`);
  }
  return lines.length ? lines.join('\n') : '  // no writeable fields';
}

function renderRelations(s) {
  const out = [];
  const rels = normalizeRelations(s);
  for (const [name, def] of Object.entries(rels)) {
    if (def.fromShorthand) continue;
    out.push(name);
  }
  return out;
}

function renderAggregations(s) {
  return (s.aggregations || []).filter(
    (a) => a && typeof a.name === 'string' && Array.isArray(a.pipeline)
  );
}

function aggregationParamShape(a) {
  if (!a.params || !Object.keys(a.params).length) return '';
  const lines = [];
  for (const [name, def] of Object.entries(a.params)) {
    const t =
      def.type === 'number'
        ? 'number'
        : def.type === 'boolean'
        ? 'boolean'
        : 'string';
    lines.push(`    ${name}${def.required ? '' : '?'}: ${t};`);
  }
  return ' { ' + lines.join(' ').replace(/\s+/g, ' ').trim() + ' }';
}

/**
 * Per-schema client interface. Methods listed: list, get, create,
 * update, delete, plus restore / history / search / aggregate /
 * file uploads / state-machine transitions where applicable.
 */
function clientInterfaceBody(s, symbolName = (x) => toPascalCase(x.path)) {
  const T = symbolName(s);
  const lines = [];
  lines.push(
    `  list(params?: ListParams<${T}Include>): Promise<ListResponse<${T}>>;`
  );
  lines.push(
    `  get(id: string, opts?: { include?: ${T}Include[] }): Promise<${T}>;`
  );
  lines.push(
    `  create(record: ${T}Writeable, opts?: IdempotentCreateOpts): Promise<${T}>;`
  );
  lines.push(
    `  update(id: string, record: Partial<${T}Writeable>): Promise<${T}>;`
  );
  lines.push(
    `  delete(id: string): Promise<DeleteResult>;`
  );
  if (s.softDelete !== false) {
    lines.push(`  restore(id: string): Promise<void>;`);
  }
  if (s.audit !== false) {
    lines.push(
      `  history(id: string, params?: { page?: number }): Promise<ListResponse<AuditEntry>>;`
    );
  }
  if ((s.fields || []).some((f) => f && f.searchable)) {
    lines.push(
      `  search(q: string, params?: ListParams<${T}Include>): Promise<ListResponse<${T}>>;`
    );
  }
  // Per-aggregation
  for (const a of renderAggregations(s)) {
    const params = aggregationParamShape(a);
    lines.push(
      `  ${a.name}(args${params ? ':' : '?:'}${params || ' Record<string, never>'}): Promise<unknown[]>;`
    );
  }
  // Per-relation explicit traversal helpers
  const rels = normalizeRelations(s);
  for (const [name, def] of Object.entries(rels)) {
    if (def.fromShorthand) continue;
    const target = symbolName({ path: def.target, version: s.version });
    if (def.kind === 'hasMany') {
      lines.push(`  ${name}(id: string): Promise<${target}[]>;`);
    } else {
      lines.push(`  ${name}(id: string): Promise<${target} | null>;`);
    }
  }
  // Per-state-machine transition
  for (const f of stateMachineFieldsOf(s)) {
    const verb = `transition${f.name.charAt(0).toUpperCase()}${f.name.slice(1)}`;
    const states = f.stateMachine.states.map((x) => JSON.stringify(x)).join(' | ');
    lines.push(`  ${verb}(id: string, to: ${states}): Promise<${T}>;`);
  }
  // Per-file-field upload / fetch URL / delete
  for (const f of (s.fields || []).filter((x) => x && x.type === 'File')) {
    const verb = f.name.charAt(0).toUpperCase() + f.name.slice(1);
    lines.push(
      `  upload${verb}(id: string, file: Blob | File): Promise<FileMeta>;`
    );
    lines.push(`  fetch${verb}Url(id: string): Promise<string>;`);
    lines.push(`  delete${verb}(id: string): Promise<void>;`);
  }
  return lines.join('\n');
}

/**
 * Emit a TypeScript object-literal property key. Unquoted when the
 * path is a valid TS identifier (`account`, `rel_account`); quoted
 * via JSON.stringify when it isn't (`mcp-doc`, `123resource`,
 * anything with hyphens / leading digits / unusual characters).
 * Without this guard, schemas with non-identifier paths would emit
 * invalid TS.
 */
function tsPropertyKey(name) {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(name)
    ? name
    : JSON.stringify(name);
}

function clientFactoryEntries(
  loaded,
  symbolName = (x) => toPascalCase(x.path),
  clientKey = (x) => x.path
) {
  return loaded
    .map(({ s }) => {
      const T = symbolName(s);
      const stateMachineNames = stateMachineFieldsOf(s).map((f) => f.name);
      const aggNames = renderAggregations(s).map((a) => a.name);
      const fileNames = (s.fields || [])
        .filter((f) => f && f.type === 'File')
        .map((f) => f.name);
      const relations = renderRelations(s);
      const config = {
        path: s.path,
        version: s.version,
        softDelete: s.softDelete !== false,
        audit: s.audit !== false,
        searchable: (s.fields || []).some((f) => f && f.searchable),
        aggregations: aggNames,
        relations,
        stateMachineFields: stateMachineNames,
        fileFields: fileNames,
      };
      return `  ${tsPropertyKey(clientKey(s))}: makeResourceClient<${T}, ${T}Writeable, ${T}Include>(client, ${JSON.stringify(
        config
      )}) as ${T}Client,`;
    })
    .join('\n');
}

/**
 * Build the entire generated file as a single string. `entries` is
 * the schema registry projection used by tests with a stub loader;
 * the CLI builds it from the live loader.
 *
 * Naming: schemas are normally keyed by `s.path` alone (one version
 * per resource is the common case). When two entries collide on
 * `path` (e.g. `v1/contact` AND `v2/contact` are both loaded), we
 * disambiguate by stamping the version into the symbol name and the
 * client key — `Contact` becomes `V1Contact` / `V2Contact`, the
 * client key `contact` becomes `v1/contact` / `v2/contact`. Without
 * this, the generated file would carry duplicate `interface Contact`
 * declarations and one would silently overwrite the other in the
 * factory return object.
 */
function generateClient(entries, { baseUrl = '' } = {}) {
  const sorted = entries.slice().sort((a, b) => {
    const byPath = a.s.path.localeCompare(b.s.path);
    if (byPath !== 0) return byPath;
    return String(a.s.version || '').localeCompare(String(b.s.version || ''));
  });
  // Detect path collisions across versions. Single-version schemas
  // get the clean names; only the colliding ones carry version
  // qualifiers.
  const pathCount = new Map();
  for (const { s } of sorted) {
    pathCount.set(s.path, (pathCount.get(s.path) || 0) + 1);
  }
  const collides = (path) => (pathCount.get(path) || 0) > 1;
  const symbolName = (s) =>
    collides(s.path)
      ? toPascalCase(`${s.version}_${s.path}`)
      : toPascalCase(s.path);
  const clientKey = (s) =>
    collides(s.path) ? `${s.version}/${s.path}` : s.path;
  const out = [];
  out.push(HEADER);
  out.push(
    "import {\n" +
      "  ApiOptions,\n" +
      "  AuditEntry,\n" +
      "  AvailableTransitions,\n" +
      "  DeleteResult,\n" +
      "  FileMeta,\n" +
      "  IdempotentCreateOpts,\n" +
      "  ListParams,\n" +
      "  ListResponse,\n" +
      "  buildHttpClient,\n" +
      "  makeResourceClient,\n" +
      "} from './davepi-runtime';\n"
  );

  // Per-schema types + interfaces
  for (const { s } of sorted) {
    const T = symbolName(s);
    const includes = renderRelations(s);
    out.push(`// ============================================================`);
    out.push(`// ${clientKey(s)}`);
    out.push(`// ============================================================`);
    out.push(`export interface ${T} {`);
    out.push(readShapeBody(s, symbolName));
    out.push(`}`);
    out.push(`export interface ${T}Writeable {`);
    out.push(writeShapeBody(s));
    out.push(`}`);
    out.push(
      `export type ${T}Include = ${
        includes.length
          ? includes.map((r) => JSON.stringify(r)).join(' | ')
          : 'never'
      };`
    );
    out.push(`export interface ${T}Client {`);
    out.push(clientInterfaceBody(s, symbolName));
    out.push(`}`);
    out.push('');
  }

  // Aggregate client type
  out.push('export interface DavepiClient {');
  for (const { s } of sorted) {
    out.push(`  ${tsPropertyKey(clientKey(s))}: ${symbolName(s)}Client;`);
  }
  out.push('}');
  out.push('');

  out.push('export function createDavepiClient(opts: ApiOptions = {}): DavepiClient {');
  out.push(`  const client = buildHttpClient({ baseUrl: ${JSON.stringify(baseUrl)}, ...opts });`);
  out.push('  return {');
  out.push(clientFactoryEntries(sorted, symbolName, clientKey));
  out.push('  };');
  out.push('}');
  out.push('');

  return out.join('\n');
}

module.exports = {
  generateClient,
  // Exported for testing — callers may want to assert specific
  // mappings without re-rendering the whole file.
  toPascalCase,
  typeOf,
  mapBareType,
};
